remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme
title: Advisory services in food products development and food safety
description: Alitudo S Ltd, Zagreb, Croatia
show_downloads: [false]
